version: "3.9"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbt_tutorial
    ports:
      - 5432:5432
